baseURL = "/"
languageCode = "en-us"
title = "Emanuel's Site"
theme = "archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    mode = "light"
    useCDN = false
    subtitle = "A place for me to archive and share notes, research, and hobbies"

[[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/ergz"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3
