baseURL = "/"
languageCode = "en-us"
title = "Emanuel's Site"
description = " "
theme = "archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    mode = "light"
    useCDN = false

[[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/ergz"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "All posts"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4